Branding = "Default Theme"
Description = ""

#"https://unpkg.com/mvp.css"
# paper.min.css
# Stylesheets = ["sizes.css", "theme-light.css", "paper.min.css", "minimal.css", "responsive.css"]
Stylesheets = ["sizes.css", "theme-light.css", "https://unpkg.com/papercss@1.6.1/dist/paper.min.css", "minimal.css", "responsive.css"]
RootStylesheets = ["reset.css", "fonts.css", "layout.css"]
PathName = ""

[Nav]
  HTML = ""
  File = "nav.md"

[Header]
  HTML = ""
  File = "header.md"

[Article]
  HTML = ""
  File = "article.md"

[Footer]
  HTML = ""
  File = "footer.md"

[Sidebar]
  HTML = ""
  File = "sidebar.md"
