#!/bin/sh
# Creates a new theme demo directory.
# Copies the wide directory to the dir named on the command line,
# then searches and replaces the theme name in .md files as required.
# You still have a number of things to personalize, documented below.
[ ! $1 ] && echo "Please specify the new theme name" && exit 1

# Replace with your favorite command line editor, which is
# of course nvim
editor=nvim
mkdir -p $1
echo "Copying the wide theme to ${1}" 
cp wide/*.md $1
[ ! -d $1 ] && echo "theme directory ${1} doesn't exist" && exit 1
declare -a filenames=(
	'dark'
	'light'
	'light-sidebar-left'
	'light-sidebar-right'
	'dark-sidebar-left'
	'dark-sidebar-right'
	)

dest=$1

# Displays prompt, and waits for user to answer 
# with either a Y or N. Repeats prompt until
# it gets one of those two.
# Return 0 if answer was Y,
# return 1 if answer was N.
# 
# Answer is in the global variable $?
#
# Example usage:
#   wait_for_yes "Please enter y or n "
wait_for_yes() {
  while :; do
    #echo -n "${1} "
    echo "${1} "
    read answer
    case "$answer" in
      [Yy])
        return 0
        ;;
      [Nn])
        return 1
        ;;
      *)
        ;;
    esac
  done
}



for file in "${filenames[@]}"
do
	# Display the commmand to execute...
	echo "${file}"
	# And execute the command
  # Thank you, Sundeep!
  # https://stackoverflow.com/questions/62254934/zsh-on-macos-1-not-expanding-in-a-sed-script?noredirect=1#comment110102949_62254934
  sed -i.bak -E 's/theme=\"(.*).*\"/\theme=\"'$1'\"/' $dest/$file.md > $dest/$file.bak
  #sed -E 's/theme=\"(.*).*\"/\theme=\"'$1'\"/' < $dest/$file 
done
  sed -i.bak -E 's/DemoTheme=\"(.*).*\"/\DemoTheme=\"'$1'\"/' $1/index.md > $1/index.bak
echo "Don't forget to fix Next in the front matter. That links to the next theme."
echo "Now customize the following:"
echo "\tReplace ${dest}/intro.md with any images, text or other material you"
echo "\twould like to precede the kitchensink with"
echo "\tReplace ${dest}/description.md with a pitch describing the theme"
echo "\tReplace ${dest}/left-sidebar-example.md with left sidebar content for this theme"
echo "\tReplace ${dest}/right-sidebar-example.md with right sidebar content for this theme"
wait_for_yes "Run nvim on these files?"
if [ $? == 0 ]; then
$editor ${dest}/index.md ${dest}/intro.md ${dest}/description.md ${dest}/left-sidebar-example.md ${dest}/right-sidebar-example.md 
fi


wait_for_yes "Delete the .bak files?"
if [ $? == 0 ]; then
rm $1/*.bak 
fi

exit 0



